# Generated by Django 5.0.6 on 2024-07-10 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Reference', max_length=128)),
                ('ref_type', models.CharField(default='Reference', max_length=128)),
                ('index', models.IntegerField()),
                ('citation', models.CharField(blank=True, default='', max_length=1048576)),
                ('doi', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('pmid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('pmcid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.paper')),
            ],
            options={
                'unique_together': {('paper', 'type', 'ref_type', 'index')},
            },
        ),
    ]
