# Generated by Django 4.2.4 on 2023-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_alter_collection_create_time_and_more'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='view.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='papers',
            field=models.ManyToManyField(to='view.paper'),
        ),
    ]
