# Generated by Django 4.2.4 on 2023-08-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_members_group_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='display_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
