# Generated by Django 4.2.4 on 2023-09-01 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_display_name_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
