# Generated by Django 4.2.4 on 2023-09-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCheckInInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
