# Generated by Django 5.0 on 2023-12-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_customcheckininterval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCheckInInterval',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
