# Generated by Django 4.0.3 on 2022-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('creator_weixin_id', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(verbose_name='date published')),
                ('doi', models.CharField(max_length=100)),
                ('pmid', models.CharField(max_length=20)),
                ('pmcid', models.CharField(max_length=100)),
                ('arxiv_id', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=200)),
                ('publish_year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=65536)),
            ],
        ),
    ]
