# Generated by Django 4.0.3 on 2022-03-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
