# Generated by Django 4.0.3 on 2022-03-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_paper_is_open_paper_is_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_preprint',
            field=models.BooleanField(default=False),
        ),
    ]
