# Generated by Django 4.0.3 on 2022-03-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_label_paper_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.CharField(default='', max_length=65536),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='urls',
            field=models.CharField(default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='paper',
            name='arxiv_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='comments',
            field=models.CharField(default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='paper',
            name='creator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pmcid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pmid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publish_year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
