# Generated by Django 4.0.3 on 2022-03-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_paper_authors_paper_full_text_paper_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.CharField(default='', max_length=65536),
        ),
    ]
