# Generated by Django 4.0.3 on 2022-04-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_label_desc_label_owner_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossRefCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DOI', 'DOI'), ('PMID', 'PMID'), ('PMCID', 'PMCID'), ('arXiv', 'arXiv'), ('CNKI', 'CNKI')], default='DOI', max_length=10)),
                ('key', models.CharField(default='', max_length=100)),
                ('value', models.CharField(max_length=100000)),
            ],
        ),
    ]
