# Generated by Django 4.0.3 on 2022-04-01 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_crossrefcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=50000)),
                ('parent', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_fields', models.CharField(default='', max_length=1000)),
                ('is_private', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='members', to='view.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='view.user')),
                ('papers', models.ManyToManyField(to='view.paper')),
            ],
        ),
    ]
