# Generated by Django 4.0.3 on 2022-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='delete_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
