# Generated by Django 4.2.4 on 2023-09-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0009_alter_collection_create_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrossRefCache',
        ),
    ]
