# Generated by Django 4.2.5 on 2023-09-14 21:19

from django.db import migrations, models

def extract_year_from_date(apps, schema_editor):
    Paper = apps.get_model('view', 'Paper')
    for obj in Paper.objects.all():
        if obj.pub_date is None:
            obj.pub_year = None
        else:
            obj.pub_year = obj.pub_date.year
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_delete_crossrefcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pub_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(extract_year_from_date),
    ]
