# Generated by Django 4.2.5 on 2023-09-22 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def link_users(apps, schema_editor):
    CustomUser = apps.get_model('view', 'User')
    AuthUser = apps.get_model('auth', 'User')

    for custom_user in CustomUser.objects.all():
        matching = AuthUser.objects.filter(username=custom_user.username)
        if matching.exists():
            user = matching.first()
            user.auth_user = custom_user
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view', '0011_paper_pub_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_unionid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RunPython(link_users),
    ]
