# Generated by Django 4.2.5 on 2023-09-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0013_alter_collection_desc_alter_label_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
