# Generated by Django 4.2.5 on 2023-09-22 15:59

from django.db import migrations


def remain_nickname(apps, schema_editor):
    User = apps.get_model('view', 'User')

    for user in User.objects.all():
        if user.nickname is None:
            user.nickname = user.username
        if user.nickname is None:
            user.nickname = User.weixin_id
        if user.nickname is None:
            user.nickname = User.name
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0014_remove_paper_labels_delete_collection_delete_label'),
    ]

    operations = [
        migrations.RunPython(remain_nickname),
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weixin_id',
        ),
    ]
