# Generated by Django 4.2.5 on 2023-09-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0015_remove_user_last_login_time_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_preprint',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_review',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pub_date',
        ),
    ]
