# Generated by Django 5.0 on 2023-12-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0016_remove_paper_full_text_remove_paper_is_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wx_unionid',
        ),
    ]
