# Generated by Django 5.0 on 2023-12-27 07:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_old_data(apps, schema_editor):
    old_model = apps.get_model('group', 'Group')
    new_model = apps.get_model('view', 'GroupProfile')
    for old_obj in old_model.objects.all():
        new_obj = new_model.objects.create(
            name=old_obj.name,
            display_name=old_obj.display_name,
            desc=old_obj.desc,
            create_time=old_obj.create_time,
        )
        for member in old_obj.members.all():
            new_obj.members.add(member)
        for paper in old_obj.papers.all():
            new_obj.papers.add(paper)

    old_model = apps.get_model('group', 'CustomCheckInInterval')
    new_model = apps.get_model('view', 'CustomCheckInInterval')
    for old_obj in old_model.objects.all():
        new_obj = new_model.objects.create(
            year=old_obj.year,
            month=old_obj.month,
            deadline=old_obj.deadline,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0018_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCheckInInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('display_name', models.CharField(default='', max_length=128)),
                ('desc', models.CharField(default='', max_length=2000)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('members', models.ManyToManyField(to='view.userprofile')),
                ('papers', models.ManyToManyField(to='view.paper')),
            ],
        ),
        migrations.RunPython(copy_old_data),
    ]
