# Generated by Django 5.0 on 2024-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0020_alter_userprofile_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
    ]
