# Generated by Django 5.0 on 2024-01-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0021_userprofile_debug_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_for', to='view.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='view.userprofile')),
            ],
            options={
                'unique_together': {('user', 'alias')},
            },
        ),
    ]
