# Generated by Django 5.0.4 on 2024-04-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0023_usersession_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wx_unionid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
