# Generated by Django 5.0.6 on 2024-07-01 06:51

import django.db.models.deletion
from django.db import migrations, models

def migrate_paper_data(apps, schema_editor):
    Review = apps.get_model('view', 'Review')
    Paper = apps.get_model('view', 'Paper')

    for review in Review.objects.all():
        paper = Paper.objects.create(
            journal=review.journal,
            pub_year=review.pub_year,
            title=review.title,
            authors=review.authors,
            abstract=review.abstract,
            urls=review.urls,
            doi=review.doi,
            pmid=review.pmid,
            arxiv_id=review.arxiv_id,
            pmcid=review.pmcid,
            cnki_id=review.cnki_id
        )
        review.paper = paper
        review.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0025_rename_paper_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(blank=True, default='', max_length=200)),
                ('pub_year', models.IntegerField(blank=True, default=None, null=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('authors', models.CharField(blank=True, default='', max_length=4000)),
                ('abstract', models.CharField(blank=True, default='', max_length=4000)),
                ('urls', models.CharField(blank=True, default='', max_length=1000)),
                ('doi', models.CharField(blank=True, default='', max_length=100)),
                ('pmid', models.CharField(blank=True, default='', max_length=20)),
                ('arxiv_id', models.CharField(blank=True, default='', max_length=30)),
                ('pmcid', models.CharField(blank=True, default='', max_length=100)),
                ('cnki_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='view.paper'),
        ),
        migrations.RunPython(migrate_paper_data),
        migrations.RemoveField(
            model_name='review',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='review',
            name='arxiv_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cnki_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='review',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pmcid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pmid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pub_year',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='urls',
        ),
    ]
