# Generated by Django 5.0.6 on 2024-07-01 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0026_paper_remove_review_abstract_remove_review_arxiv_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.paper'),
        ),
    ]
