# Generated by Django 5.0.6 on 2024-07-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0027_alter_review_paper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='papers',
            new_name='reviews',
        ),
    ]
