# Generated by Django 5.0.6 on 2024-07-01 07:48

from django.db import migrations, models

def copy_pub_year_to_pub_date(apps, schema_editor):
    Paper = apps.get_model('view', 'Paper')
    for paper in Paper.objects.all():
        paper.pub_date = str(paper.pub_year)
        paper.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0028_rename_papers_groupprofile_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pub_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(copy_pub_year_to_pub_date),
    ]
