# Generated by Django 5.0.6 on 2024-07-01 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0029_paper_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('color', models.CharField(default='#B6CFF5', max_length=7)),
                ('desc', models.CharField(default='', max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaperTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='read', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('memo', models.CharField(blank=True, default='', max_length=2000)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.paper')),
                ('trackings', models.ManyToManyField(blank=True, to='view.papertracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaperLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.label')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.paper')),
            ],
            options={
                'unique_together': {('label', 'paper')},
            },
        ),
    ]
