# Generated by Django 5.0.6 on 2024-07-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0030_label_papertracking_recommendation_paperlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='institutes',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='paper',
            name='arxiv_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cnki_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pmcid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pmid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pub_date',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='paper',
            name='urls',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
    ]
