# Generated by Django 5.0.6 on 2024-07-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0031_paper_institutes_paper_keywords_alter_paper_abstract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cn', models.CharField(blank=True, default='', max_length=4096)),
                ('abstract_cn', models.CharField(blank=True, default='', max_length=65536)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='view.paper')),
            ],
        ),
    ]
