# Generated by Django 5.0.6 on 2024-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0032_papertranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='delete_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
