# Generated by Django 5.0.6 on 2024-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0033_recommendation_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='view.label'),
        ),
        migrations.DeleteModel(
            name='PaperLabel',
        ),
    ]
