# Generated by Django 5.0.6 on 2024-07-01 23:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

def add_existed_details(apps, schema_editor):
    Recommendation = apps.get_model('view', 'Recommendation')
    RecommendationDetails = apps.get_model('view', 'RecommendationDetails')
    for r in Recommendation.objects.all():
        for t in r.trackings.all():
            d = RecommendationDetails(recommendation=r, recommend_time = r.create_time,
                                      type = t.type, value = t.value, label = t.label, memo = t.memo)
            d.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0034_review_labels_delete_paperlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(default='read', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('memo', models.CharField(blank=True, default='', max_length=2000)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.label')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='view.recommendation')),
            ],
        ),
        migrations.RunPython(add_existed_details),
    ]
