# Generated by Django 5.0.6 on 2024-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0037_alter_papertranslation_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='language',
            field=models.CharField(default='eng', max_length=20),
        ),
    ]
