# Generated by Django 5.0.6 on 2024-07-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0038_paper_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationdetails',
            name='recommend_time',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
