# Generated by Django 5.0.6 on 2024-07-02 19:01

from django.db import migrations, models


def copy_details_to_labels(apps, schema_editor):
    Recommendation = apps.get_model('view', 'Recommendation')
    RecommendationDetails = apps.get_model('view', 'RecommendationDetails')
    for r in Recommendation.objects.all():
        for d in RecommendationDetails.objects.filter(recommendation=r):
            if r.labels.filter(pk=d.label.pk).count() == 0:
                r.labels.add(d.label)

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0039_remove_recommendationdetails_recommend_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='view.label'),
        ),
        migrations.RunPython(copy_details_to_labels),
    ]
