# Generated by Django 5.0.6 on 2024-07-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0040_recommendation_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendationDetails',
        ),
    ]
