# Generated by Django 5.0.6 on 2024-07-04 17:51

import django.utils.timezone
from django.db import migrations, models

def init_paper_create_time_paper_update_time(apps, schema_editor):
    Paper = apps.get_model('view', 'Paper')
    for paper in Paper.objects.all():
        if paper.review_set.all().count() > 0:
            paper.review_set.all().order_by('create_time')[0].create_time
            paper.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0041_delete_recommendationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paper',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(init_paper_create_time_paper_update_time)
    ]
