# Generated by Django 5.0.6 on 2024-07-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0042_paper_create_time_paper_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='paper',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
