# Generated by Django 5.0.6 on 2024-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0043_alter_paper_options_alter_paper_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubMedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('index', models.IntegerField()),
                ('doi', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('pmid', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['doi'], name='doi_idx'), models.Index(fields=['pmid'], name='pmid_idx')],
            },
        ),
    ]
