# Generated by Django 5.0.6 on 2024-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0045_alter_pubmedindex_doi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='delete_time',
            new_name='read_time',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
