# Generated by Django 5.0.6 on 2024-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0046_rename_delete_time_recommendation_read_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='arxiv_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cnki_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pmcid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pmid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pub_year',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='read_time',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
