# Generated by Django 5.0.6 on 2024-07-07 13:01

from django.db import migrations, models

def copy_comments_to_comment(apps, schema_editor):
    Review = apps.get_model('view', 'Review')
    for review in Review.objects.all():
        review.comment = review.comments
        review.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0047_alter_paper_arxiv_id_alter_paper_cnki_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1048576),
        ),
        migrations.RunPython(
            copy_comments_to_comment,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
    ]
