# Generated by Django 5.0.6 on 2024-07-07 18:07

from django.db import migrations, models

def copy_paper_institutes_to_paper_affiliations_and_more(apps, schema_editor):
    Paper = apps.get_model('view', 'Paper')
    for paper in Paper.objects.all():
        paper.affiliations = paper.institutes
        paper.save()

class Migration(migrations.Migration):

    dependencies = [
        ('view', '0048_remove_review_comments_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='affiliations',
            field=models.CharField(blank=True, default='', max_length=1048576),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.CharField(blank=True, default='', max_length=1048576),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(blank=True, default='', max_length=1048576),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=1048576),
        ),
        migrations.AlterField(
            model_name='paper',
            name='urls',
            field=models.CharField(blank=True, default='', max_length=1048576),
        ),
        migrations.RunPython(copy_paper_institutes_to_paper_affiliations_and_more),
        migrations.RemoveField(
            model_name='paper',
            name='institutes',
        ),
    ]
