# Generated by Django 5.0.6 on 2024-07-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0049_remove_paper_institutes_paper_affiliations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCheckInInterval',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='papertracking',
            name='label',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='papertranslation',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='review',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='papertracking',
            name='user',
        ),
        migrations.DeleteModel(
            name='PubMedIndex',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='useralias',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='useralias',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='useralias',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupProfile',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='PaperTranslation',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='PaperTracking',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserAlias',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
