"""Generate a member reading-interest report for a paper-sharing group.

This is the manual entry point. It reads every member's paper comments (reviews /
check-ins) for a group and uses the configured LLM (DeepSeek) to write each
member's reading profile, plus a group-level aggregate. It then writes a JSON
report to `backend/reports/<group>_member_report.json`.

The website reads this JSON via `GET /api/groups/<group>/member-report/` and lets
visitors click a member ("打卡人") to open their complete evaluation profile.

The script requires `DEEPSEEK_API_KEY` to be set in `backend/.env` (see
`backend/.env.example`). It fails fast if the key is missing or the API is
unreachable, rather than producing template-based output.

Usage::

    uv run manage.py generate_member_report [--group xiangma] [--workers 4] [--delay 0.5]
"""

import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime

from django.core.management.base import BaseCommand, CommandError

from core.models import GroupProfile
from core.member_report import (
    LLMBridge,
    build_group_aggregate,
    build_member_profiles,
    generate_llm_profile,
    read_member_summaries,
    write_html_report,
    write_index,
    write_member_profile,
    write_report,
)


def _provider_name(base_url: str) -> str:
    """Derive a human-friendly provider label from the API base URL."""
    url = (base_url or "").lower()
    if "deepseek" in url:
        return "DeepSeek"
    if "openai" in url or "openai.com" in url:
        return "OpenAI"
    return base_url.split("//")[-1].split("/")[0] or "LLM"


class Command(BaseCommand):
    help = "Generate per-member reading-interest profiles and a group report."

    def add_arguments(self, parser):
        parser.add_argument("--group", default="xiangma", help="Group name (default: xiangma).")
        parser.add_argument(
            "--min-count",
            type=int,
            default=1,
            help="Minimum number of reviews a member must have to be included (default: 1).",
        )
        parser.add_argument(
            "--delay",
            type=float,
            default=1.0,
            help="Seconds to pause between members to avoid rate limits (default: 1.0; use 0 for none).",
        )
        parser.add_argument(
            "--workers",
            type=int,
            default=4,
            help="Number of concurrent LLM requests (default: 4).",
        )
        parser.add_argument(
            "--user",
            type=int,
            default=None,
            help="Only regenerate a single member (by user id); rebuild the index from disk.",
        )

    def handle(self, *args, **options):
        group_name = options["group"]
        min_count = options["min_count"]
        delay = max(0.0, options["delay"])
        workers = max(1, options["workers"])
        user_id = options["user"]

        if not GroupProfile.objects.filter(name=group_name).exists():
            raise CommandError(f"Group '{group_name}' does not exist.")

        # The report is generated by an LLM (DeepSeek); the key is required.
        llm = LLMBridge.from_settings()
        if llm is None:
            raise CommandError(
                "DEEPSEEK_API_KEY is required to generate the member report. "
                "Create backend/.env from backend/.env.example and set the key "
                "(see https://platform.deepseek.com)."
            )

        self.stdout.write(f"Reading reviews for group '{group_name}' ...")
        profiles = build_member_profiles(group_name, min_count=min_count)
        if not profiles:
            raise CommandError("No members found for this group.")

        # Aggregate is computed from the data (deterministic); it never relies on
        # the LLM, so it is always recomputed from all member records.
        aggregate = build_group_aggregate(group_name, profiles)

        if user_id:
            self._update_one(group_name, llm, profiles, aggregate, user_id)
            return

        self._generate_all(group_name, llm, profiles, aggregate, delay, workers)

    def _generate_all(self, group_name, llm, profiles, aggregate, delay, workers):
        """Generate every member's profile in parallel; write each on success.

        Each profile is generated concurrently (LLM calls are I/O-bound, so a
        thread pool scales well). Every member that succeeds is written to its own
        file immediately, so a failure in one member never blocks the others and
        a single member can be re-run later with `--user`.
        """
        total = len(profiles)
        self.stdout.write(
            f"Generating {total} member profiles with {llm.model} "
            f"(workers={workers}) ..."
        )

        def run_one(profile):
            ok = generate_llm_profile(profile, llm)
            error = llm.last_error or "unknown"
            return profile, ok, error

        successful = []
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {executor.submit(run_one, p): p for p in profiles}
            for index, future in enumerate(as_completed(futures), start=1):
                profile, ok, error = future.result()
                if ok:
                    # Write this member's own file as soon as it is ready.
                    write_member_profile(group_name, profile)
                    successful.append(profile)
                    self.stdout.write(f"  [{index}/{total}] {profile.name}")
                else:
                    self.stdout.write(
                        self.style.WARNING(
                            f"  [{index}/{total}] skipped {profile.name}: {error}"
                        )
                    )
                if delay:
                    time.sleep(delay)

        if not successful:
            raise CommandError("No member profiles could be generated.")

        generator = self._generator(llm)
        json_path = write_report(group_name, aggregate, successful, generator=generator)
        html_path = write_html_report(
            group_name, aggregate, successful, generator=generator
        )
        self.stdout.write(
            self.style.SUCCESS(
                f"Report written to {json_path} and {html_path}\n"
                f"  members generated: {len(successful)}/{total}\n"
                f"  model: {generator['provider']} / {generator['model']}\n"
                "  The website will pick this up at "
                f"/api/groups/{group_name}/member-report/"
            )
        )

    def _update_one(self, group_name, llm, profiles, aggregate, user_id):
        """Regenerate a single member and rebuild the index from disk."""
        target = next((p for p in profiles if p.user_id == user_id), None)
        if target is None:
            raise CommandError(f"Member with user id {user_id} not found.")

        self.stdout.write(f"Generating {target.name} ...")
        if not generate_llm_profile(target, llm):
            raise CommandError(
                f"LLM generation failed for {target.name}: {llm.last_error or 'unknown'}"
            )

        write_member_profile(group_name, target)
        summaries = read_member_summaries(group_name)
        generator = self._generator(llm)
        index_path = write_index(group_name, aggregate, summaries, generator=generator)
        self.stdout.write(
            self.style.SUCCESS(
                f"Updated {target.name} and rebuilt {index_path}\n"
                f"  members on disk: {len(summaries)}"
            )
        )

    def _generator(self, llm):
        return {
            "mode": "llm",
            "provider": _provider_name(llm.base_url),
            "model": llm.model,
            "generated_at": datetime.now().astimezone().isoformat(),
        }
