# Generated by Django 5.0.7 on 2024-07-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paper_pub_year_alter_recommendation_read_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='language',
            field=models.CharField(blank=True, default='eng', max_length=20),
        ),
    ]
