# Generated by Django 5.1.1 on 2024-09-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paper_journal_abbreviation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PubMedIndex',
        ),
    ]
