# Generated by Django 6.0.5 on 2026-05-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_personal_tracking_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_time',
            new_name='checkin_at',
        ),
    ]
